"""Browser live-capture audio contract shared by transcode and live analysis."""

from __future__ import annotations

BROWSER_LIVE_SAMPLE_RATE_HZ = 16_000
BROWSER_LIVE_CHANNEL_COUNT = 2

BROWSER_LIVE_SYSTEM_CHANNEL_INDEX = 0
BROWSER_LIVE_MICROPHONE_CHANNEL_INDEX = 1

BROWSER_LIVE_SYSTEM_SOURCE = "system"
BROWSER_LIVE_MICROPHONE_SOURCE = "microphone"

BROWSER_LIVE_SOURCE_NAME_BY_CHANNEL = {
    BROWSER_LIVE_SYSTEM_CHANNEL_INDEX: BROWSER_LIVE_SYSTEM_SOURCE,
    BROWSER_LIVE_MICROPHONE_CHANNEL_INDEX: BROWSER_LIVE_MICROPHONE_SOURCE,
}
