"""add_transcript_status

Revision ID: 1b9068cd18fd
Revises: b0642ad3bbf6
Create Date: 2025-11-29 17:05:00.612779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1b9068cd18fd'
down_revision: Union[str, Sequence[str], None] = 'b0642ad3bbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('transcript_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'transcript_status')
    # ### end Alembic commands ###
