"""Add People CRM fields and tags

Revision ID: 2c696b1d8401
Revises: 354c15ea791e
Create Date: 2025-12-29 19:56:04.432328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c696b1d8401'
down_revision: Union[str, Sequence[str], None] = '354c15ea791e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.create_table('p_tags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p_tags_name'), 'p_tags', ['name'], unique=False)
    op.create_table('people_tags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('global_speaker_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['global_speaker_id'], ['global_speakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['p_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'global_speaker_id', 'tag_id')
    )
    op.add_column('global_speakers', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('global_speakers', sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('global_speakers', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('global_speakers', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('global_speakers', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_column('global_speakers', 'notes')
    op.drop_column('global_speakers', 'phone_number')
    op.drop_column('global_speakers', 'email')
    op.drop_column('global_speakers', 'company')
    op.drop_column('global_speakers', 'title')
    op.drop_table('people_tags')
    op.drop_index(op.f('ix_p_tags_name'), table_name='p_tags')
    op.drop_table('p_tags')
    # ### end Alembic commands ###
