"""add_is_voiceprint_locked

Revision ID: 2d3f24296534
Revises: 8ea23b91dd74
Create Date: 2026-01-14 00:25:15.505528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3f24296534'
down_revision: Union[str, Sequence[str], None] = '8ea23b91dd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_speakers', sa.Column('is_voiceprint_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('people_tags', 'global_speaker_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('people_tags', 'tag_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people_tags', 'tag_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('people_tags', 'global_speaker_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('global_speakers', 'is_voiceprint_locked')
    # ### end Alembic commands ###
