"""add has_seen_demo_recording to users

Revision ID: 354c15ea791e
Revises: 17ccdc4c7f69
Create Date: 2025-12-23 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '354c15ea791e'
down_revision = ('17ccdc4c7f69', 'f8e2c3a4b5d6', '6c8e287a3f04')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('users', sa.Column('has_seen_demo_recording', sa.Boolean(), nullable=True))
    # Fill existing rows with False (or True if simpler, but False matches default)
    op.execute("UPDATE users SET has_seen_demo_recording = false")
    op.alter_column('users', 'has_seen_demo_recording',
               existing_type=sa.Boolean(),
               nullable=False,
               server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('users', 'has_seen_demo_recording')
    # ### end Alembic commands ###
