"""add_proxy_path_to_recording

Revision ID: 3bc9c0a1afb2
Revises: 7910599426d9
Create Date: 2025-12-06 18:34:38.731208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3bc9c0a1afb2'
down_revision: Union[str, Sequence[str], None] = '7910599426d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('proxy_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'proxy_path')
    # ### end Alembic commands ###
