"""add upload_progress

Revision ID: 3dfcbf84e595
Revises: bdb5cd767728
Create Date: 2025-12-11 17:20:36.495230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfcbf84e595'
down_revision: Union[str, Sequence[str], None] = 'bdb5cd767728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('upload_progress', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'upload_progress')
    # ### end Alembic commands ###
