"""add_invitations_and_roles

Revision ID: 5220faa5a93e
Revises: 3bc9c0a1afb2
Create Date: 2025-12-08 00:13:46.430234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5220faa5a93e'
down_revision: Union[str, Sequence[str], None] = '3bc9c0a1afb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.create_table('invitations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_code'), 'invitations', ['code'], unique=True)
    
    # Add role as nullable first
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Update existing rows
    op.execute("UPDATE users SET role = 'admin' WHERE is_superuser = true")
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    # Make non-nullable
    op.alter_column('users', 'role', nullable=False)
    
    op.add_column('users', sa.Column('invitation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'invitations', ['invitation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invitation_id')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_invitations_code'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
