"""add_parent_id_to_tags

Revision ID: 5e7c4f3bb0b8
Revises: a1b2c3d4e5f6
Create Date: 2025-12-21 09:59:40.947015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7c4f3bb0b8'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('tags', sa.Column('parent_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tags', 'tags', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'parent_id')
    # ### end Alembic commands ###
