"""fix_people_tag_pk

Revision ID: 6d60823e9b27
Revises: 2c696b1d8401
Create Date: 2025-12-29 20:26:02.513495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d60823e9b27'
down_revision: Union[str, Sequence[str], None] = '2c696b1d8401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop table to reset corrupted PK/Identity state
    op.drop_table('people_tags')
    
    # Recreate table with correct structure
    op.create_table('people_tags',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.BigInteger(), sa.Identity(), primary_key=True, nullable=False),
        sa.Column('global_speaker_id', sa.BigInteger(), nullable=False),
        sa.Column('tag_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['global_speaker_id'], ['global_speakers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['p_tags.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('global_speaker_id', 'tag_id', name='unique_person_tag')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_person_tag', 'people_tags', type_='unique')
    op.alter_column('people_tags', 'tag_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('people_tags', 'global_speaker_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
