"""add_error_message_to_transcript

Revision ID: 6e01255c91d7
Revises: 1b9068cd18fd
Create Date: 2025-11-29 17:32:12.065866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e01255c91d7'
down_revision: Union[str, Sequence[str], None] = '1b9068cd18fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'error_message')
    # ### end Alembic commands ###
