"""Add celery_task_id and CANCELLED status

Revision ID: 8ea23b91dd74
Revises: 7da64886cc65
Create Date: 2026-01-13 15:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ea23b91dd74'
down_revision: Union[str, Sequence[str], None] = '5c0af37b3101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('recordings', sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Handle Enum update for PostgreSQL
    # Using a safe approach to add the value if it doesn't exist
    op.execute("ALTER TYPE recordingstatus ADD VALUE IF NOT EXISTS 'CANCELLED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('recordings', 'celery_task_id')
    # Use explicit cast or temporary column for downgrading enum is complex in Postgres, 
    # usually better to leave the enum value or handle carefully.
    # For now, we skip removing the enum value as it's generally safe.
    # ### end Alembic commands ###
