"""add_trim_offsets_to_recordings

Revision ID: a3f1c8d92e64
Revises: 9f2d7c6b4a10
Create Date: 2026-05-16 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a3f1c8d92e64'
down_revision: Union[str, Sequence[str], None] = '9f2d7c6b4a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('recordings', sa.Column('trim_start_s', sa.Float(), nullable=True))
    op.add_column('recordings', sa.Column('trim_end_s', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_column('recordings', 'trim_end_s')
    op.drop_column('recordings', 'trim_start_s')
    # ### end Alembic commands ###
