"""add_notes_status_to_transcript

Revision ID: b0642ad3bbf6
Revises: 17ccdc4c7f69
Create Date: 2025-11-29 16:34:45.855611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b0642ad3bbf6'
down_revision: Union[str, Sequence[str], None] = '17ccdc4c7f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('transcripts', sa.Column('notes_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_column('transcripts', 'notes_status')
    # ### end Alembic commands ###
