"""add calendar sync tables

Revision ID: b5bedab42e47
Revises: a7b4d3e1f920
Create Date: 2026-04-11 13:35:05.283995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5bedab42e47'
down_revision: Union[str, Sequence[str], None] = 'a7b4d3e1f920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_provider_configs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=512), nullable=True),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_provider_configs_provider'), 'calendar_provider_configs', ['provider'], unique=True)
    op.create_table('calendar_connections',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('granted_scopes', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('sync_error', sa.String(length=512), nullable=True),
    sa.Column('last_sync_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_account_id', name='uq_calendar_connection_user_provider_account')
    )
    op.create_index(op.f('ix_calendar_connections_email'), 'calendar_connections', ['email'], unique=False)
    op.create_index(op.f('ix_calendar_connections_provider'), 'calendar_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_calendar_connections_provider_account_id'), 'calendar_connections', ['provider_account_id'], unique=False)
    op.create_index(op.f('ix_calendar_connections_sync_status'), 'calendar_connections', ['sync_status'], unique=False)
    op.create_index(op.f('ix_calendar_connections_user_id'), 'calendar_connections', ['user_id'], unique=False)
    op.create_table('calendar_sources',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('connection_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_calendar_id', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_zone', sa.String(length=128), nullable=True),
    sa.Column('colour', sa.String(length=32), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_window_start', sa.DateTime(), nullable=True),
    sa.Column('sync_window_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'provider_calendar_id', name='uq_calendar_source_connection_remote')
    )
    op.create_index(op.f('ix_calendar_sources_connection_id'), 'calendar_sources', ['connection_id'], unique=False)
    op.create_index(op.f('ix_calendar_sources_is_selected'), 'calendar_sources', ['is_selected'], unique=False)
    op.create_index(op.f('ix_calendar_sources_provider_calendar_id'), 'calendar_sources', ['provider_calendar_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('calendar_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('external_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'provider_event_id', name='uq_calendar_event_calendar_remote')
    )
    op.create_index(op.f('ix_calendar_events_calendar_id'), 'calendar_events', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_end_date'), 'calendar_events', ['end_date'], unique=False)
    op.create_index(op.f('ix_calendar_events_ends_at'), 'calendar_events', ['ends_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_is_all_day'), 'calendar_events', ['is_all_day'], unique=False)
    op.create_index(op.f('ix_calendar_events_provider_event_id'), 'calendar_events', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_date'), 'calendar_events', ['start_date'], unique=False)
    op.create_index(op.f('ix_calendar_events_starts_at'), 'calendar_events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_status'), 'calendar_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_events_status'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_starts_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_date'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_provider_event_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_is_all_day'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_ends_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_end_date'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_calendar_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_calendar_sources_provider_calendar_id'), table_name='calendar_sources')
    op.drop_index(op.f('ix_calendar_sources_is_selected'), table_name='calendar_sources')
    op.drop_index(op.f('ix_calendar_sources_connection_id'), table_name='calendar_sources')
    op.drop_table('calendar_sources')
    op.drop_index(op.f('ix_calendar_connections_user_id'), table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_sync_status'), table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_provider_account_id'), table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_provider'), table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_email'), table_name='calendar_connections')
    op.drop_table('calendar_connections')
    op.drop_index(op.f('ix_calendar_provider_configs_provider'), table_name='calendar_provider_configs')
    op.drop_table('calendar_provider_configs')
    # ### end Alembic commands ###
