"""add_cascades_for_user_deletion

Revision ID: bdb5cd767728
Revises: 5220faa5a93e
Create Date: 2025-12-08 01:38:23.879127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb5cd767728'
down_revision: Union[str, Sequence[str], None] = '5220faa5a93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.alter_column('chat_messages', 'recording_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('chat_messages_user_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_recording_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_messages', 'recordings', ['recording_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('invitations_created_by_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('recording_speakers', 'recording_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('recording_speakers_global_speaker_id_fkey'), 'recording_speakers', type_='foreignkey')
    op.drop_constraint(op.f('recording_speakers_recording_id_fkey'), 'recording_speakers', type_='foreignkey')
    op.create_foreign_key(None, 'recording_speakers', 'recordings', ['recording_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recording_speakers', 'global_speakers', ['global_speaker_id'], ['id'], ondelete='SET NULL')
    op.alter_column('recording_tags', 'recording_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('recording_tags', 'tag_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('recording_tags_recording_id_fkey'), 'recording_tags', type_='foreignkey')
    op.drop_constraint(op.f('recording_tags_tag_id_fkey'), 'recording_tags', type_='foreignkey')
    op.create_foreign_key(None, 'recording_tags', 'recordings', ['recording_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recording_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transcripts', 'recording_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('transcripts_recording_id_fkey'), 'transcripts', type_='foreignkey')
    op.create_foreign_key(None, 'transcripts', 'recordings', ['recording_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.create_foreign_key(op.f('transcripts_recording_id_fkey'), 'transcripts', 'recordings', ['recording_id'], ['id'])
    op.alter_column('transcripts', 'recording_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'recording_tags', type_='foreignkey')
    op.drop_constraint(None, 'recording_tags', type_='foreignkey')
    op.create_foreign_key(op.f('recording_tags_tag_id_fkey'), 'recording_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('recording_tags_recording_id_fkey'), 'recording_tags', 'recordings', ['recording_id'], ['id'])
    op.alter_column('recording_tags', 'tag_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('recording_tags', 'recording_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'recording_speakers', type_='foreignkey')
    op.drop_constraint(None, 'recording_speakers', type_='foreignkey')
    op.create_foreign_key(op.f('recording_speakers_recording_id_fkey'), 'recording_speakers', 'recordings', ['recording_id'], ['id'])
    op.create_foreign_key(op.f('recording_speakers_global_speaker_id_fkey'), 'recording_speakers', 'global_speakers', ['global_speaker_id'], ['id'])
    op.alter_column('recording_speakers', 'recording_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_created_by_id_fkey'), 'invitations', 'users', ['created_by_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_recording_id_fkey'), 'chat_messages', 'recordings', ['recording_id'], ['id'])
    op.create_foreign_key(op.f('chat_messages_user_id_fkey'), 'chat_messages', 'users', ['user_id'], ['id'])
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('chat_messages', 'recording_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
