"""add_multi_tenant_support

Revision ID: da065320c05b
Revises: d78775e75757
Create Date: 2025-11-27 21:19:15.101154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da065320c05b'
down_revision: Union[str, Sequence[str], None] = 'd78775e75757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('global_speakers', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('ix_global_speakers_name'), table_name='global_speakers')
    op.create_index(op.f('ix_global_speakers_name'), 'global_speakers', ['name'], unique=False)
    op.create_foreign_key(None, 'global_speakers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('recordings', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'recordings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('tags', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_column('users', 'settings')
    op.drop_column('users', 'force_password_change')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.drop_column('tags', 'user_id')
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.drop_column('recordings', 'user_id')
    op.drop_constraint(None, 'global_speakers', type_='foreignkey')
    op.drop_index(op.f('ix_global_speakers_name'), table_name='global_speakers')
    op.create_index(op.f('ix_global_speakers_name'), 'global_speakers', ['name'], unique=True)
    op.drop_column('global_speakers', 'user_id')
    # ### end Alembic commands ###
