"""Add color to speakers

Revision ID: e1ba697397de
Revises: b011c25e42fb
Create Date: 2025-11-27 00:59:16.593683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1ba697397de'
down_revision: Union[str, Sequence[str], None] = 'b011c25e42fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_speakers', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recording_speakers', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording_speakers', 'color')
    op.drop_column('global_speakers', 'color')
    # ### end Alembic commands ###
