import { describe, expect, it, vi } from "vitest";

// Characterization guard on the public runtime surface of the API layer, which
// is split across resource modules behind a barrel. That barrel must re-export
// exactly these names, plus the default axios instance, so a dropped or renamed
// export fails here rather than silently breaking one of the many import sites.
// Type-only exports are erased at runtime and are guarded by the TypeScript
// build instead.

vi.mock("axios", () => ({
  default: {
    create: vi.fn(() => ({
      patch: vi.fn(),
      put: vi.fn(),
      get: vi.fn(),
      post: vi.fn(),
      delete: vi.fn(),
      interceptors: {
        request: { use: vi.fn() },
        response: { use: vi.fn() },
      },
    })),
  },
}));

describe("api public surface", () => {
  it("exports the same named runtime members after decomposition", async () => {
    const api = await import("./api");
    const runtimeNames = Object.keys(api)
      .filter((name) => name !== "default")
      .sort();

    expect(runtimeNames).toMatchInlineSnapshot(`
      [
        "API_BASE_URL",
        "DOCUMENT_SIZE_WARNING_BYTES",
        "SUPPORTED_DOCUMENT_FORMATS",
        "VISION_ONLY_DOCUMENT_FORMATS",
        "addPersonalDictionaryWord",
        "addSpellcheckIgnoredWord",
        "addTagToRecording",
        "applyVoiceprintAction",
        "archiveRecording",
        "batchAddTagToRecordings",
        "batchArchiveRecordings",
        "batchPermanentlyDeleteRecordings",
        "batchRemoveTagFromRecordings",
        "batchRestoreRecordings",
        "batchSoftDeleteRecordings",
        "checkFFmpeg",
        "clearChatHistory",
        "copyNotesTemplate",
        "createGlobalSpeaker",
        "createInvitation",
        "createNotesTemplate",
        "createPeopleTag",
        "createTag",
        "createUser",
        "createUserTask",
        "deleteDocument",
        "deleteGlobalSpeaker",
        "deleteGlobalSpeakerEmbedding",
        "deleteInvitation",
        "deleteModel",
        "deleteNotesTemplate",
        "deletePeopleTag",
        "deleteRecording",
        "deleteRecordingSpeaker",
        "deleteTag",
        "deleteUser",
        "deleteUserTask",
        "deleteVoiceprint",
        "discardRecordingCapture",
        "disconnectCalendarConnection",
        "downloadBackupFile",
        "downloadDocument",
        "exportAudio",
        "exportBackupAsync",
        "exportContent",
        "extractAllVoiceprints",
        "extractVoiceprint",
        "fetchProxyModels",
        "finalizeRecordingCapture",
        "findAndReplace",
        "findAndReplaceNotes",
        "generateNotes",
        "generateNotesStructure",
        "getAdminHealth",
        "getBackupStatus",
        "getCalendarAuthorisationStartUrl",
        "getCalendarDashboardSummary",
        "getCalendarOverview",
        "getCalendarProviderStatuses",
        "getChatHistory",
        "getConnectedApps",
        "getCurrentUser",
        "getDemoRecording",
        "getDocuments",
        "getDownloadProgress",
        "getGeneratedNotesStructure",
        "getGlobalSpeakers",
        "getInitialConfig",
        "getInvitations",
        "getLanguageOptions",
        "getModelsStatus",
        "getNotes",
        "getOAuthAuthorizeInfo",
        "getPausedRecordings",
        "getPeopleTags",
        "getPersonalDictionary",
        "getRecording",
        "getRecordingAnalytics",
        "getRecordingCalendarEventCandidates",
        "getRecordingInfo",
        "getRecordingStreamUrl",
        "getRecordings",
        "getRecordingsCalendar",
        "getSettings",
        "getSpeakerSegments",
        "getSpellcheckIgnoredWords",
        "getSupportedAudioFormats",
        "getSystemStatus",
        "getTags",
        "getTaskStatus",
        "getTelemetryStatus",
        "getTlsFingerprint",
        "getTranscriptUtterances",
        "getUserMe",
        "getUserNotes",
        "getUserTasks",
        "getUsers",
        "getVersion",
        "getVisionSupport",
        "importAudio",
        "importBackup",
        "inferSpeakers",
        "initRecording",
        "isActiveRecordingConflictDetail",
        "linkRecordingCalendarEvent",
        "listModels",
        "listNotesTemplates",
        "login",
        "logout",
        "markTelemetryNoticeShown",
        "mergeRecordingSpeakers",
        "mergeSpeakers",
        "pauseRecordingCapture",
        "permanentlyDeleteRecording",
        "prepareModels",
        "previewNotesPrompt",
        "promoteToGlobalSpeaker",
        "recalibrateSpeaker",
        "registerUser",
        "removePersonalDictionaryWord",
        "removeSpellcheckIgnoredWord",
        "removeTagFromRecording",
        "renameRecording",
        "reparseDocument",
        "reportRecordingCaptureSources",
        "reprocessRecording",
        "resetNotesTemplate",
        "restoreRecording",
        "resumeRecordingCapture",
        "revokeConnectedApp",
        "revokeInvitation",
        "scanMatches",
        "seedDemoData",
        "setupSystem",
        "softDeleteRecording",
        "splitLocalSpeaker",
        "splitSpeaker",
        "startCalendarAuthorisation",
        "streamChatMessage",
        "submitOAuthDecision",
        "syncCalendarConnection",
        "updateCalendarColor",
        "updateCalendarProviderConfiguration",
        "updateCalendarSelection",
        "updateGlobalSpeaker",
        "updateMeetingEdgeFocus",
        "updateNotes",
        "updateNotesTemplate",
        "updatePasswordMe",
        "updatePeopleTag",
        "updateRecordingMaxSpeakers",
        "updateSettings",
        "updateSpeaker",
        "updateSpeakerColor",
        "updateTag",
        "updateTelemetryEnabled",
        "updateTranscriptSegmentSpeaker",
        "updateTranscriptSegmentText",
        "updateTranscriptSegments",
        "updateTranscriptUtteranceSpeaker",
        "updateTranscriptUtteranceText",
        "updateUser",
        "updateUserMe",
        "updateUserNotes",
        "updateUserRole",
        "updateUserTask",
        "uploadBackupChunked",
        "uploadDocument",
        "uploadRecordingSegment",
        "validateInvitation",
        "validateLLM",
      ]
    `);
  });

  it("preserves the default axios instance export", async () => {
    const api = await import("./api");
    const instance = api.default as unknown as Record<string, unknown>;

    expect(typeof instance.get).toBe("function");
    expect(typeof instance.post).toBe("function");
    expect(typeof instance.put).toBe("function");
    expect(typeof instance.patch).toBe("function");
    expect(typeof instance.delete).toBe("function");
  });
});
